name: Test Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print masked secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Testing secrets..."
          echo "API_KEY starts with: ${API_KEY:0:5}*****"
